### ISSUE TITLE
[Bug]: brick/geo Package not installed as part of package dependencies

### ISSUE THREAD

**Issue by ylynfatt** [ShabuShabu/laravel-postgis#5]
### What happened?

I installed `laravel-postgis` via composer, however, while I was working on using this package within a test application, I noticed it could not find `Brick\Geo\Point` for use in a Model cast. It seems as though the `brick/geo` package wasn't installed as one of the dependencies during the `composer require` process.

It might help if it were installed by default along with the `laravel-postgis` package or if perhaps the README could be updated to state that `brick/geo` would need to be installed separately if the functionality it provides is needed.

### How to reproduce the bug

1. Start a fresh Laravel project
2. Install laravel-postgis via composer.
3. Try to setup a model cast based on example in README.md

### Package Version

0.4.0

### PHP Version

8.3.14

### Laravel Version

11.34.2

### Which operating systems does with happen with?

macOS

**Comment by boris-glumpler** [comment]
The `brick/geo` integration is part of the next version. I meant to release it a few days ago, but life happened. You can already use it if you install the `develop` branch, but I still need to test the model cast.

I’ll try to get a new version released today and will keep this ticket open till then!

**Comment by boris-glumpler** [comment]
I've just released v0.5.0, which includes the `brick/geo` integration.

**Comment by ylynfatt** [comment]
Ok great. Thanks @boris-glumpler
